toppingskorea/toppings-client

- src/components/Skeleton/index.ts
> fix: #8 export default 구문 받아오는 쪽에서 이름 설정할 수 있도록

- src/@types/index.d.ts
- src/components/Common/InternalLink/InternalLink.tsx
- src/components/Common/InternalLink/InternalLink.types.ts
- src/components/Common/InternalLink/index.ts
- src/components/Common/index.ts
- src/hooks/index.ts
- src/hooks/useInternalRouter.ts
- src/pages/login/redirect/index.page.tsx
- type safe
- useRouter
- Link 
#18 
- 💬 질문 사항이에요!
> feat: type safe route

- src/@types/images.d.ts
- tsconfig.json
- SVG types any - > 개정확완벽타입
- 💬 질문 사항이에요!
> fix: Add SVG Types

- package.json
- src/components/Common/TextField/Input.tsx
- src/components/Section/SearchNationality/index.tsx
- src/components/Skeleton/Box.tsx
- src/components/Skeleton/Paragraph.tsx
- src/utils/common/index.ts
- src/utils/common/queryChunk.ts
- 국가 선택 touchable하게 설정
- size 함수사용하도록 컨벤션 설정
- 💬 질문 사항이에요!
> fix: width height raw가 아닌 size함수 사용하도록 수정

- apps/client/apis/post/index.ts
- apps/client/apis/profile/index.ts
- apps/client/apis/register/index.ts
- apps/client/apis/restaurant/index.ts
- apps/client/pages/post/[id].page.tsx
- apps/client/pages/profile/edit/index.page.tsx
- apps/client/pages/profile/index.page.tsx
- apps/client/pages/profile/posts/index.page.tsx
- packages/next-config/next.config.js
백엔드에서 api 버져닝을 도입하면서 endpoint수정하였습니다.
- 💬 질문 사항이에요!
> hotfix: api v1 엔드포인트 적용

- apps/admin/.turbo/turbo-build.log
- apps/admin/@types/restaurant.d.ts
- apps/admin/@types/review.d.ts
- apps/admin/components/Common/Sidebar/Sidebar.constants.ts
- apps/admin/components/Reviews/ReviewDetail/index.tsx
- apps/admin/components/Reviews/ReviewTable/index.tsx
- apps/admin/components/Reviews/index.ts
- apps/admin/pages/review/[id].page.tsx
- apps/admin/pages/reviews.page.tsx
- apps/admin/server/review/apis.ts
- apps/admin/server/review/index.ts
- apps/admin/server/review/keys.ts
- apps/admin/server/review/mutations.tsx
- apps/admin/server/review/queries.ts
- apps/client/.turbo/turbo-build.log
- node_modules/.cache/turbo/314bd279aaa7c821-meta.json
- node_modules/.cache/turbo/bf8284833ccce9d9-meta.json
- 리뷰 목록 보기 구현 완료하였습니다.
- 리뷰를 관리자가 관리할 수 있습니다(승인 / 거절)
http://127.0.0.1:3000/reviews 에서 리뷰 목록을 봅니다
http://127.0.0.1:3000/reviews/{id} 에서 승인 및 거절을 해봅니다.
승인 거절 모두 성공하면 테스트 성공
- 💬 질문 사항이에요!
https://github.com/toppingskorea/toppings-server/issues/29
DTO에 추가 field가 필요하므로 부탁드린상태입니다. => 반영완료했습니다
> feat(admin): 리뷰 목록 보기 구현 완료하였습니다. 리뷰를 관리자가 관리할 수 있습니다(승인 / 거절)

- .github/auto_assign.yml
- .github/labeler.yml
- apps/client/components/Post/detail/Info/index.tsx
- apps/client/components/Profile/profile/Info/index.tsx
- apps/client/components/Review/detail/ImageCarouselWrapper/index.tsx
- apps/client/components/Util/OpenGraph/index.tsx
- apps/client/components/Util/index.ts
- apps/client/pages/404.page.tsx
- apps/client/pages/_document.page.tsx
- apps/client/pages/index.page.tsx
- apps/client/pages/map/index.page.tsx
- apps/client/pages/notice/index.page.tsx
- apps/client/pages/post/[id].page.tsx
- apps/client/pages/post/add/index.page.tsx
- apps/client/pages/profile/edit/eatingHabits/index.page.tsx
- apps/client/pages/profile/edit/index.page.tsx
- apps/client/pages/profile/edit/nationality/index.page.tsx
- apps/client/pages/profile/menu/index.page.tsx
- apps/client/pages/profile/posts/index.page.tsx
- apps/client/pages/profile/reviews/index.page.tsx
- apps/client/pages/profile/saved/index.page.tsx
- apps/client/pages/recent/eatingHabit.page.tsx
- apps/client/pages/recent/nationality.page.tsx
- apps/client/pages/recent/restaurant.page.tsx
- apps/client/pages/register/eatingHabits/index.page.tsx
- apps/client/pages/register/nationality/index.page.tsx
- apps/client/pages/review/add/[restaurantId].page.tsx
- apps/client/pages/search/[type].page.tsx
- 페이지별 OpenGraph 기능을 작업하여,  SEO및 사용자의 편의성을 증가시킵니다.
- OpenGraph 컴포넌트 제작
- 각페이지에서 상단의 탭 부분에 잘 적용이 되었는지 확인합니다.
- post를 공유했을때 제대로 OG가 작동하여 성공했는지 확인합니다.
- 💬 질문 사항이에요!
> feat(client): 페이지별 OpenGraph 기능을 작업하여,  SEO및 사용자의 편의성을 증가시킵니다.

- .github/auto_assign.yml
- apps/client/@types/restaurant.d.ts
- apps/client/components/Post/detail/Info/index.tsx
- apps/client/pages/post/[id].page.tsx
- post의 상세 DTO에는thumbnail이 없으므로 images[0]으로 처리합니다
- 지금까지 이미지에 대한 SEO가 작동하지 않았습니다.
- localhost:3000/post/42 에 들어가신뒤 head태그에 og:image가 설정되어있는지 확인해주세요.
- 💬 질문 사항이에요!
> fix(client): post의 상세 DTO에는thumbnail이 없으므로 images[0]으로 처리합니다

- apps/admin/components/Posts/PostDetail/PostDetail.hooks.ts
- apps/admin/components/Posts/PostDetail/index.tsx
- apps/admin/components/Reviews/ReviewDetail/ReviewDetail.hooks.ts
- apps/admin/components/Reviews/ReviewDetail/index.tsx
- 음식점 리젝 사유를 고르지 않고 리젝버튼을 클릭했을때 리젝이 반영되면 안됩니다.
- 리뷰 리젝 사유를 고르지 않고 리젝버튼을 클릭했을때 리젝이 반영되면 안됩니다.
- 💬 질문 사항이에요!
> feat(admin): admin에서 리젝 사유가 없을 시, 음식점과 리뷰를 리젝시키지 못하게 합니다.

- apps/client/pages/review/[id].page.tsx
- 리뷰 상세를 SEO에 최적화 하기 위해, SSR 처리를 합니다
- http://localhost:3000/review/97 OG가 제대로 적용되었는지 판단합니다.
- 💬 질문 사항이에요!
> fix(client): 리뷰 상세를 SEO에 최적화 하기 위해, SSR 처리를 합니다

- README.md
- README.md
- 링크 연동이 잘못된 것이 없는지 확인합니다.
- 💬 질문 사항이에요!
> chore(root): README.md 파일 작성

- apps/client/@types/route.d.ts
- apps/client/pages/about/index.page.tsx
- apps/client/pages/profile/menu/index.page.tsx
- feat(client): 약관과 개인정보 처리 방침 링크를 연결합니다
- http://localhost:3000/about 페이지에서 2개의 링크를 클릭해봅니다.
- http://localhost:3000/profile/menu에서 링크 클릭시 about으로 이동되는지 확인합니다.
- 💬 질문 사항이에요!
> feat(client): 약관과 개인정보 처리 방침 링크를 연결합니다

- apps/client/components/Layout/TopNavigator/index.tsx
- apps/client/pages/recent/eatingHabit.page.tsx
- apps/client/pages/recent/index.page.tsx
- apps/client/pages/recent/nationality.page.tsx
- apps/client/pages/recent/restaurant.hooks.tsx
- apps/client/pages/register/eatingHabits/index.page.tsx
- apps/client/pages/register/nationality/index.page.tsx
- apps/client/recoil/atoms/navigation.ts
- apps/client/server/register/apis.ts
- TopNavigator의 backbutton을 보여주지 않을 수 있도록 설정한뒤 회원가입 및 Map관련 페이지에 적용합니다.
- 회원가입 / 맵 관련 페이지만 topnavigator를 적용했습니다.
- 회원가입 로직을 따라가며 top navigator가 정확히 세팅되었는지 확인합니다.
- 맵 로직을 따라가며 top navigator가 정확히 세팅되었는지 확인합니다.
- 나머지 페이지 닫기 버튼 / 뒤로가기 버튼 구분하여 수정완료하기
- 💬 질문 사항이에요!
> feat(client): TopNavigator의 backbutton을 보여주지 않을 수 있도록 설정한뒤 회원가입 및 Map관련 페이지에 적용합니다.

- apps/client/components/Common/Modal/AlertModal/AlertModal.stories.tsx
- apps/client/components/Skeleton/Box/Box.stories.tsx
- apps/client/components/Skeleton/Circle/Circle.stories.tsx
- apps/client/components/Skeleton/Paragraph/Paragraph.stories.tsx
-  Meta => ComponentMeta 로 타입을 최신버전으로 업그레이드합니다.
- stories 파일에 정확히 Meta타입이 아닌 ComponentMeta타입을 사용하고 있는지 확인합니다.
- 💬 질문 사항이에요!
> fix(client): Meta => ComponentMeta 로 타입을 최신버전으로 업그레이드합니다.

- apps/admin/.turbo/turbo-build.log
- apps/client/.turbo/turbo-build.log
- apps/client/components/Common/Modal/AlertModal/AlertModal.stories.tsx
- apps/client/components/Common/Modal/AlertModal/index.tsx
- apps/client/components/Layout/TopNavigator/index.tsx
- apps/client/components/Post/PostDetailPage/Reviews/ReviewItem/index.tsx
- apps/client/components/Recent/RecentPage/index.tsx
- AlertModal에 대한 리팩토링을 수행하였습니다!(#77 )
- http://localhost:3000/recent 에서 removeall 버튼의 기능이 잘 작동하는 지 확인해주세요.
- 💬 질문 사항이에요!
> refactor(client) : AlertModal에 대한 리팩토링을 적용합니다.

- apps/client/pages/_app.page.tsx
- 도메인 변경으로 인해 sentry allow url을 수정합니다
- 💬 질문 사항이에요!
> fix(client): 도메인 변경으로 인해 sentry allow url을 수정합니다

- apps/client/components/Review/ReviewAddPage/ReviewAddPage.hooks.tsx
- apps/client/components/Review/ReviewAddPage/index.tsx
- 리뷰 추가 및 수정 페이지 hooks 파일로 분리하여 가독성을 향상시킵니다.
- 리뷰 작성 / 수정이 잘 작동하는지 확인합니다.
- 💬 질문 사항이에요!
> refactor(client): 리뷰 추가 및 수정 페이지 hooks 파일로 분리하여 가독성을 향상시킵니다.

- apps/client/components/Recent/FilterEatingHabitPage/index.tsx
- apps/client/components/Recent/FilterNationalityPage/index.tsx
- apps/client/components/Recent/FilterRestaurantPage/FilterRestaurantPage.hooks.tsx
- apps/client/components/Recent/FilterRestaurantPage/index.tsx
- apps/client/components/Recent/TagFamily/TagFamily.constants.ts
- apps/client/components/Recent/TagFamily/index.tsx
- apps/client/components/Recent/index.ts
- apps/client/pages/recent/eatingHabit.page.tsx
- apps/client/pages/recent/filter/eatingHabit.page.tsx
- apps/client/pages/recent/filter/nationality.page.tsx
- apps/client/pages/recent/filter/restaurant.page.tsx
- apps/client/pages/recent/nationality.page.tsx
- apps/client/pages/recent/restaurant.page.tsx
- recent 하위에 있던 eatingHabit, restaurant, nationality 페이지들을 filter 하위 경로로 변경합니다.(#78 )
- http://localhost:3000/recent 의 하단에 있는 tag를 사용하여 잘 이동되는지 확인합니다.
- 💬 질문 사항이에요!
> refactor(client): recent 하위 페이지들의 새로운 폴더 경로를 구축합니다.

- apps/client/components/Common/HeartWithNumber/index.tsx
- apps/client/components/Common/RestaurantCard/index.tsx
- apps/client/components/Recent/RecentPage/index.tsx
- apps/client/components/Recent/RecentRestaurantPage/index.tsx
- apps/client/components/Recent/TagFamily/index.tsx
- recent page에서 remove all 간격 수정
- restaurant page에서 리스트간의 간격 수정
- TagFamily 간격 수정
- http://localhost:3000/recent
- http://localhost:3000/recent/restaurant
각 페이지에서 변경사항을 확인합니다
- 💬 질문 사항이에요!
> feat(client) : Map QA part - 2

- apps/client/components/Map/MapPage/index.tsx
- 맵에 찍히는 핀들 아래에 식당 이름을 표기하였습니다.
- http://localhost:3000/map 주소에서 맵 밑에 핀들이 잘 찍혀 있는지 체크합니다.
- 💬 질문 사항이에요!
> feat(client): 맵에 찍히는 핀 밑에 식당 이름을 표기합니다.

- apps/client/components/Common/LoadingIndicator/Seek/Seek.stories.tsx
- apps/client/components/Common/LoadingIndicator/Seek/index.tsx
- apps/client/components/Common/LoadingIndicator/index.tsx
- apps/client/components/Common/index.ts
- apps/client/components/Post/PostAddPage/CTAButton/Edit/index.tsx
- apps/client/components/Post/PostAddPage/CTAButton/Register/index.tsx
- apps/client/components/Profile/ProfileEditPage/RegisterButton/index.tsx
- apps/client/components/Review/ReviewAddPage/ReviewAddPage.hooks.tsx
- apps/client/components/Review/ReviewAddPage/index.tsx
- LoadingIndicator Seek 컴포넌트 생성
- 리뷰 작성시 로딩인디게이터 보여줄 수 있도록 작업
- 게시글 작성시 로딩인디게이터 보여줄 수 있도록 작업
- 프로필 수정시 로딩인디게이터 보여줄 수 있도록 작업
- 리뷰 작성시 로딩인디게이터 보여주는지 확인합니다.
- 게시글 작성시 로딩인디게이터 보여주는지 확인합니다.
- 프로필 수정시 로딩인디게이터 보여주는지 확인합니다.
- 스토리북 Seek 컴포넌트를 확인합니다.
- 💬 질문 사항이에요!
네트워크느리게 하고 확인해보세용!!
> feat(client): 무거운 백엔드 API와 통신할 경우 UX향상을 위해 로딩 인디게이터를 보여줍니다.

- apps/client/components/About/AboutPage/index.tsx
about 페이지에 Bottom navigator를 설정합니다
- About페이지에서 아래 네비게이터가 잘 보이는지 확인합니다.
- 💬 질문 사항이에요!
> fix(client): about 페이지에 Bottom navigator를 설정합니다

- apps/client/components/About/AboutPage/index.tsx
about 페이지에 SEO를 설정합니다
- 💬 질문 사항이에요!
> fix(client): about 페이지에 SEO를 설정합니다

- apps/client/components/Search/SearchPage/SearchPage.hooks.ts
- apps/client/components/Search/SearchPage/index.tsx
- apps/client/contexts/DeviceInfoProvider/DeviceInfoContext.ts
- apps/client/contexts/DeviceInfoProvider/DeviceInfoProvider.tsx
- apps/client/contexts/DeviceInfoProvider/index.ts
- apps/client/contexts/DeviceInfoProvider/useDeviceInfo.ts
- apps/client/contexts/index.ts
- apps/client/hooks/index.ts
- apps/client/hooks/useBooleanState.ts
- apps/client/pages/_app.page.tsx
- 사용자의 접속 환경을 감지할 수 있는 contexts를 구성합니다.
- search/restaurant페이지 UX를 개선합니다
- 💬 질문 사항이에요!
> fix(client): search/restaurant페이지 UX를 개선합니다 & 사용자의 접속 환경을 감지할 수 있는 contexts를 구성합니다.

- apps/client/components/Common/Gallery/Gallery.hooks.ts
- apps/client/components/Common/Gallery/index.tsx
- Image Gallery의 max값 만큼 사진이 등록되면 input을 숨깁니다
- http://localhost:3000/post/add 에 들어가서 사진을 5장올렸을때 input이 사라지면 성공입니다.
- 💬 질문 사항이에요!
> fix(client): Image Gallery의 max값 만큼 사진이 등록되면 input을 숨깁니다

- apps/client/components/Recent/History/index.tsx
- Recent page의 empty view의 텍스트가 badge와 간격이 없이 붙어있던 점을 수정하였습니다.
- 127.0.0.1:3000/recent 로 들어가서 remove all을 한 후에 엠티뷰를 확인합니다.
- 💬 질문 사항이에요!
> Fix(client): Top으로부터 떨어져 있는 엠티뷰 텍스트를 피그마와 통일합니다.

- apps/client/components/Common/Gallery/index.tsx
- apps/client/components/Common/ImageCarousel/index.tsx
- apps/client/components/Profile/ProfileEditPage/UserInfo/ProfileImage/index.tsx
- apps/client/components/Profile/ProfilePage/Info/index.tsx
- 2/8 이미지 비율에 대해서 논의된 건입니다.
- 💬 질문 사항이에요!
> fix(client): 이미지를 화질 좋게 업로드 하고 비율을 수정합니다.

- apps/admin/@types/index.d.ts
- apps/admin/components/Posts/PostDetail/PostDetail.hooks.ts
- apps/admin/components/Reviews/ReviewDetail/index.tsx
- apps/admin/server/notice/apis.ts
- apps/admin/server/notice/index.ts
- apps/admin/server/notice/mutations.tsx
- apps/admin/server/restaurant/apis.ts
- apps/admin/server/review/apis.ts
- 음식점 / 리뷰 리젝시 알림을 보냅니다
테스트 환경에서 28080
-  음식점을 리젝시켰을때 알림이 잘 가나 확인합니다.
-  리뷰를 리젝시켰을때 알림이 잘 가나 확인합니다.
- 💬 질문 사항이에요!
> feat(admin): 음식점 / 리뷰 리젝시 알림을 보냅니다

- apps/client/components/Post/PostDetailPage/Info/index.tsx
- post detail의 description을 사용자가 복사해야할 경우가 있기 때문에 복사가능하게 user-select를 부여하였습니다.
이 부분이 정상적으로 복사가 되는지 확인합니다.
- 💬 질문 사항이에요!
> fix(client): post detail description을 복사 가능하게 합니다.

- apps/client/components/Post/PostDetailPage/Info/index.tsx
> fix(client): post detail description을 복사 가능하게 합니다 (#127)

- apps/client/constants/data/common/diets.ts
- apps/client/constants/data/common/religions.ts
Halal의 위치를 이동시킵니다 Diet로 옮기고 Muslim friendly는 뺏습니다
- 💬 질문 사항이에요!
> fix(client): Halal의 위치를 이동시킵니다

- apps/client/pages/_app.page.tsx
- sentry로 클라이언트 에러를 트래킹하기 위해서 url을 설정합니다.
- 센트리에서 로그를 확인해야합니다!
> chore(client): sentry로 클라이언트 에러를 트래킹하기 위해서 url을 설정합니다.

- apps/admin/components/Post/PostUploadPage/CTAButton/Register/index.tsx
- apps/admin/components/Post/PostUploadPage/index.tsx
- apps/admin/recoil/atoms/post.ts
- apps/admin/server/post/apis.ts
- 관리자 페이지에서 게시글 등록시에 해당 게시글 전시에 허용해준 인스타그램 사용자의 이름을 등록할 수 있습니다.
- http://127.0.0.1:3000/post/upload 접속 후에 인스타그램 아이디 선택 Input 컴포넌트가 있는지 확인합니다.
> feat(admin) : 관리자 페이지의 게시글 등록 페이지에서 사용자의 인스타 이름을 등록할 수 있습니다.

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
> sync master

- apps/admin/components/Common/Gallery/Item/index.tsx
- 게시글 업로드시
- 리뷰 업로드시
이미지에 대해 원본비율이 유지되는지 확인합니다.
> feat(client): image gallery의 이미지의 원본비율을 유지합니다

- apps/client/components/Common/Badge/index.tsx
- apps/client/components/Post/PostDetailPage/index.tsx
- 배지 컴포넌트를 사용하는 방식에서 클릭요소가 아닌 경우도 있어 수정했습니다. #145 
- http://localhost:3000/post/38 에서 Likes와 Reviews 배지에 마우스를 올려 클릭이 되는 요소가 아닌지 확인합니다.
> fix(client) : post 상세 페이지에서 Likes, Reivews 배지는 클릭 요소가 아닙니다.

- apps/client/components/Common/index.ts
- apps/client/components/Post/PostAddPage/PostAddPage.hooks.tsx
- apps/client/components/Post/PostAddPage/index.tsx
추후 유지보수를 용이하게 하기 위해 UI로직과 Business 로직을 분리합니다.
게시글이 제대로 올라가고, 수정이 되는지 확인합니다.
> refactor(client): postaddpage 를 비즈니스 로직과 UI로직을 분리합니다.

- apps/client/components/Profile/ProfileEditPage/UserInfo/index.tsx
저번에 개선점이 보여서 질문주셨는데, 기획과 논의통해서 글자수만 알려주기로 했습니다.
프로필 페이지 닉네임 힌트 워딩이 적절하게 설정되었는지 확인합니다.
> fix(client): 프로필 닉네임 hint 수정합니다.

- apps/client/components/Error/ErrorPage/index.tsx
기존에 에러페이지가 잘못된 워딩으로 되어있어서 수정합니다.
> fix(client): 에러 페이지 워딩을 수정합니다

- .eslintrc.json
- apps/client/components/Layout/TopNavigator/TopNavigator.hooks.tsx
- apps/client/components/Layout/TopNavigator/index.tsx
- topnavigator hooks 리팩토링을 진행합니다
- 한개만 export하는 경우 워닝을 제거합니다.
> refactor(client): topnavigator hooks 리팩토링을 진행합니다

- apps/admin/components/Login/LoginPage/index.tsx
- apps/admin/components/Login/LoginPage/login.hooks.ts
- login페이지의 hook의 관심사를 분리합니다. 
- 기존에는 app으로 묶여있어서 각자의 관심사가 섞여있었습니다.
> refactor(admin): login페이지의 hook의 관심사를 분리합니다.

- apps/admin/components/Review/ReviewDetail/index.tsx
- 역할을 분리하기 위해 뷰와, 비즈니스 로직을 분리합니다
> refactor(admin): 리뷰 상세 훅을 분리합니다

- apps/admin/.turbo/turbo-build.log
- apps/client/.turbo/turbo-build.log
- packages/next-config/next.config.js
- components transpile을 추가합니다.
> feat(packages) : transpilePackages를 추가합니다.

- apps/client/components/Notice/NoticePage/NotificationList/index.tsx
- apps/client/layouts/AppLayout/index.tsx
알림페이지를 위한 웹소켓을 등록합니다.
작동은 하는데 vercel 환경에서 제대로 작동하는지 확인하기 위해 develop 으로 머지합니다
> feat(client): 알림페이지를 위한 웹소켓을 등록합니다.

- apps/client/components/Notice/NoticePage/NotificationList/index.tsx
- apps/client/hooks/useWebSocket.ts
- apps/client/layouts/AppLayout/index.tsx
현재 백엔드와 쿠키 시간 싱크가 안된 이슈로 토큰이 있는 유저가 웹소켓 호출시 토큰이 만료되었으면 400 에러가 발생하기 떄문에 임시적으로 블럭처리를합니다.
> fix(client): block websocket

- apps/client/@types/emotion.d.ts
- apps/client/components/Common/Gallery/index.tsx
- apps/client/components/Common/RoundedTag/RoundedTag.tsx
- apps/client/components/Common/SnapCarousel/SnapCarousel.tsx
- apps/client/components/Post/PostAddPage/index.tsx
- apps/client/components/Recent/TagFamily/index.tsx
- apps/client/styles/GlobalCSS.tsx
- apps/client/styles/emotionTheme/colors/index.ts
- apps/client/styles/emotionTheme/dimensions/index.ts
- apps/client/styles/emotionTheme/index.ts
- apps/client/styles/emotionTheme/weighs/index.ts
- apps/client/styles/emotionTheme/zIndex/index.ts
- apps/client/styles/emotionUtils/hiddenScroll.ts
- apps/client/styles/emotionUtils/index.ts
- apps/client/styles/index.ts
- styles의 default export들을 named export로 변경합니다.
> feat(client) : styles의 default export를 named export로 변경합니다.

- apps/client/server/notice/index.ts
- apps/client/server/notice/keys.ts
- apps/client/server/notice/mutations.tsx
- apps/client/server/notice/queries.ts
- apps/client/server/post/mutations.tsx
- apps/client/server/profile/index.ts
- apps/client/server/profile/keys.ts
- apps/client/server/profile/mutations.ts
- apps/client/server/profile/queries.ts
- apps/client/server/recent/index.ts
- apps/client/server/recent/keys.ts
- apps/client/server/recent/mutations.ts
- apps/client/server/recent/queries.ts
- apps/client/server/register/mutations.ts
- apps/client/server/restaurant/index.ts
- apps/client/server/restaurant/keys.ts
- apps/client/server/restaurant/mutations.ts
- apps/client/server/restaurant/queries.ts
- apps/client/server/review/index.ts
- apps/client/server/review/keys.ts
- apps/client/server/review/mutations.ts
- apps/client/server/review/queries.ts
- server 폴더의 default export를 named export로 변경합니다.
> Feat(client) : server 폴더의 default export를 named export로 변경합니다.

- apps/admin/.turbo/turbo-build.log
- apps/client/.turbo/turbo-build.log
- packages/hooks/src/index.ts
- packages/hooks/src/useDebounce.ts
- packages/hooks/src/useInput.ts
- packages/hooks/src/useMounted.ts
- packages/hooks/src/usePreservedCallback.ts
- packages/hooks/src/usePreservedReference.ts
- hooks 폴더의 default export를 named export로 변경합니다.
> feat(packages): hooks 폴더의 default export를 named export로 변경합니다.

- apps/client/@types/route.d.ts
- apps/client/components/Layout/BottomNavigator/BottomNavigator.constants.tsx
- apps/client/components/Layout/BottomNavigator/index.tsx
- apps/client/components/Map/ViewListPage/ViewListPage.hooks.tsx
- apps/client/components/Post/PostAddPage/CTAButton/Edit/index.tsx
- apps/client/components/Post/PostAddPage/CTAButton/Register/index.tsx
- apps/client/components/Post/PostAddPage/DuplicatedOverlay/index.tsx
- apps/client/components/Profile/ProfilePostsPage/PostList/index.tsx
- apps/client/components/Recent/FilterEatingHabitPage/index.tsx
- apps/client/components/Recent/FilterNationalityPage/index.tsx
- apps/client/components/Recent/FilterRestaurantPage/FilterRestaurantPage.hooks.tsx
- apps/client/components/Recent/History/History.hooks.ts
- apps/client/components/Recent/RecentPage/index.tsx
- apps/client/components/Register/RegisterEatingHabitsPage/index.tsx
- apps/client/middleware.page.ts
- apps/client/pages/index.page.tsx
- apps/client/pages/map/index.page.tsx
- apps/client/pages/onboarding/index.page.tsx
앞으로 https://planet.toppings.co.kr/ 는 지도 페이지
기존의 index 페이지는 https://planet.toppings.co.kr/onboarding 이됩니다.
적절히 동작하는지 확인부탁드립니다!
> feat(client): map과 onboarding페이지의 라우팅을 교체합니다.

- apps/admin/layouts/AppLayout/index.tsx
- apps/admin/layouts/index.ts
- apps/admin/pages/_app.page.tsx
- apps/client/layouts/AppLayout/index.tsx
- apps/client/layouts/index.ts
- apps/client/pages/_app.page.tsx
- apps/client, apps/admin의 layouts 폴더 안의 파일들을 default export에서 named export로 변경합니다!
> feat(client, admin) : layouts 파일들을 named export로 변경합니다.

- apps/client/components/Kakao/Buttons/FilteringButton.tsx
- apps/client/components/Map/ViewListPage/ViewListPage.hooks.tsx
- apps/client/components/Post/PostDetailPage/Info/Info.hooks.tsx
- apps/client/hooks/auth/index.ts
- apps/client/hooks/auth/useProtectRouteModal.tsx
- apps/client/hooks/index.ts
- apps/client/hooks/map/index.ts
- apps/client/hooks/map/useResetRecentRecoilState.ts
- apps/client/hooks/mobile/index.ts
- apps/client/hooks/mobile/useDetectKeyboard.ts
- apps/client/hooks/useBlurController.ts
- apps/client/hooks/useBooleanState.ts
- apps/client/hooks/useInternalRouter.ts
- apps/client/hooks/useIntersectionObserver.ts
- apps/client/hooks/useOriginURL.ts
- apps/client/hooks/useScrollToTopByKeywordChange.ts
- apps/client/hooks/useSentry.ts
- apps/client/hooks/useSetNavigation.ts
- apps/client/hooks/useTokenCookie.ts
- apps/client/hooks/useWebSocket.ts
- apps/client안의 hooks 폴더의 default export를 named export로 변경합니다.
> feat(client) : hooks 폴더의 default export를 named export로 변경합니다.

- apps/client/components/Layout/BottomNavigator/BottomNavigator.hooks.tsx
- apps/client/components/Layout/BottomNavigator/index.tsx
> fix(client): icon onclick 핸들러의 함수 생성 문제해결

- apps/admin/@types/route.d.ts
- apps/admin/layouts/AppLayout/index.tsx
> fix(admin): admin route login 삭제

- apps/client/components/Common/PageLoader/index.tsx
페이지 이동시 opacity가 변경되고 있었는데 효과를 누리고 있지 못했습니다. background-color를 설정하여 부드러움을 선사하여 UX를 증진시킵니다.
페이지를 마구마구 이동시켜봅니다!
> feat(client): page 이동시 부드럽게 opacity효과를 부여합니다

- apps/client/components/Common/PageLoader/index.tsx
- apps/client/components/Notice/NoticePage/index.tsx
- apps/client/components/Profile/ProfilePage/index.tsx
- apps/client/constants/Motions.ts
> sync master 

- apps/client/components/Kakao/Buttons/ViewStatusButton.tsx
- apps/client/components/Layout/BottomNavigator/BottomNavigator.styles.ts
- apps/client/components/Layout/BottomNavigator/index.tsx
- apps/client/components/Layout/TopNavigator/TopNavigator.styles.ts
- apps/client/components/Layout/TopNavigator/index.tsx
- viewList viewMap 버튼에 touchable 부여
- bottomNavigator아이콘 클릭 가능영역을 확대합니다
- TopNavigator 양 옆 버튼의 클릭 가능한 영역을 확대합니다
> feat(client): 클릭 가능한 영역 확대 및 touchable옵션을 통해 UX를 개선합니다.

- apps/client/components/Kakao/Buttons/ViewStatusButton.tsx
- apps/client/components/Layout/BottomNavigator/BottomNavigator.styles.ts
- apps/client/components/Layout/BottomNavigator/index.tsx
- apps/client/components/Layout/TopNavigator/TopNavigator.styles.ts
- apps/client/components/Layout/TopNavigator/index.tsx
* feat(client): top nav 양 옆 버튼 클릭 가능한 영역확대
* feat(client): 하단 메뉴 이동 아이콘의 클릭 가능한 영역을 확대하여 UX를 개선합니다
* feat(client): view list view map 뱃지를 클릭 가능한 효과를 부여하여 UX를 개선합니다
> feat(client): 클릭 가능한 영역 확대 및 touchable옵션을 통해 UX를 개선합니다. (#214)

- apps/client/components/Layout/BottomNavigator/BottomNavigator.styles.ts
> fix(client): bottom navigation icon이 자연스럽게 나머지 너비를 차지하게함
